name: Build and Push
permissions:
  id-token: write
  contents: read
on:
  pull_request:
    types:
      - opend
      - synchronize
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3    

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: ${{secrets.AWS_ARN}}
        aws-region: ap-northeast-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      run: |
        docker build -t lookbook .
        docker tag lookbook:latest ${{ secrets.ECR_REPO }}
        docker push ${{ secrets.ECR_REPO }}